# Generated by Django 6.1.1 on 2026-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
