# Generated by Django 6.1.1 on 2026-09-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('CULTURALS', 'Culturals'), ('DJ NIGHT', 'DJ Night')], max_length=50),
        ),
    ]
